version: '3.8'
services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore
    ports:
      - "8080:8080"
    networks:
      - bookstore-networks

networks:
  bookstore-networks:
    driver: bridge
